import type { Metadata } from "next";
import { Outfit, Raleway } from "next/font/google";
import Header from "./_components/Header";
import "@/app/_styles/globals.css";

export const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
  weight: ["700", "800"],
});
export const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${outfit.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
